# Home AI LightDM GTK Greeter Theme

[greeter]
theme-name = Adwaita-dark
icon-theme-name = Adwaita
font-name = Sans 11
background = /usr/share/backgrounds/homeai-default.svg
user-background = false
hide-user-image = false
default-user-image = /usr/share/pixmaps/homeai-logo.png
show-indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format = %A, %B %e    %H:%M
